theme: jekyll-theme-minimal
logo: /img/logo.png
title: [STScI's Exocoffee]
description: [Website for the exoplanetary journal club at STScI]
when: [Every other Monday, 9 AM]
where: [Virtually (contact organizers for link)]
