relative_url: adfssdsdgs 
theme: jekyll-theme-minimal
logo: logo.png
title: STScI's Exocoffee
description: Website for the exoplanetary journal club at STScI
when: [Every other Monday at 9 AM.]
where: [Virtually (BlueJeans).]
